### ISSUE TITLE
Support MacOS for VSOCK over AF_UNIX

### ISSUE THREAD

**Issue by DUOLabs333** [stefano-garzarella/iperf-vsock#3]
Currently, it seems that only Linux hosts can use iperf as a vsock server of UNIX pipes. While MacOS can't act as vsock clients, there seems to be no restriction preventing them from acting as vsock hosts (over UNIX pipes).

**Comment by stefano-garzarella** [comment]
@DUOLabs333 thanks for the report.
Yep, `HAVE_VSOCK` macro depends on `linux/vm_sockets.h`, so we may use it better to support other hosts.
