### ISSUE TITLE
iperf-vsock cli doesn't show items related to vsock

### ISSUE THREAD

**Issue by justxuewei** [stefano-garzarella/iperf-vsock#6]
It's a very weird problem for me.

I built the iperf-vsock on my host. The arguments related to vsock were shown as expected:

```shell
$ ./iperf3 --help
Usage: iperf3 [-s|-c host] [options]
       iperf3 [-h|--help] [-v|--version]
...
  -B, --bind      <host>    bind to the interface associated with the address <host>
  --vsock                   use VSOCK rather than TCP
  -V, --verbose             more detailed output
...
```

After that, I copied "build" directory from host to guest, without changing anything. I did the same things in the guest. The arguments disappears from the output.

```shell
Usage: iperf [-s|-c host] [options]
       iperf [-h|--help] [-v|--version]

...
  -B, --bind      <host>    bind to a specific interface
  -V, --verbose             more detailed output
...
```

Did I do some things wrong?

**Comment by stefano-garzarella** [comment]
@justxuewei it looks like `iperf3` is using system libraries, do you have `iperf3` installed in the guest from the distro?
Can you try to remove it?

If you don't want to remove, you can try to force using your library in this way:
```
LD_LIBRARY_PATH="build/src/.libs/" build/src/.libs/iperf3
```

Otherwise, you can try to build it statically: `../configure --enable-static-bin`

**Comment by stefano-garzarella** [comment]
Using `ldd` I can see that is trying to use the system `libiperf.so` also if I build it locally:
```
$ ldd build/src/.libs/iperf3 | grep libiperf 
	libiperf.so.0 => /lib64/libiperf.so.0 (0x00007fc1b3787000)
```

Using LD_LIBRARY_PATH:
```
$ LD_LIBRARY_PATH="build/src/.libs/" ldd build/src/.libs/iperf3 | grep libiperf
	libiperf.so.0 => build/src/.libs/libiperf.so.0 (0x00007f86f9ec0000)
```

**Comment by justxuewei** [comment]
A huge thanks to @stefano-garzarella ;)

> it looks like iperf3 is using system libraries, do you have iperf3 installed in the guest from the distro?

Exactly. So I choose to build it statically.
