### ISSUE TITLE
silbing VM can not connect to each other by default due to host side vhost vsock

### ISSUE THREAD

**Issue by zhengbaowen** [stefano-garzarella/iperf-vsock#7]
Hi Bro:
sorry to bother you. 

i use this iperf vsock to send traffic between silbing vms, but i find they can not build connection. 

then i find it seems in host side of vhost-vsock, the host only receive the packets that the dest cid is host ifself. so is there anything else necessary for the changes in host side to allow silbing vms to create connection? 

thanks

**Comment by stefano-garzarella** [comment]
@zhengbaowen vhost-vsock doesn't support sibling VMs, only vhost-user-vsock supports it

**Comment by stefano-garzarella** [comment]
@zhengbaowen an example is here: https://github.com/rust-vmm/vhost-device/blob/main/vhost-device-vsock/README.md#sibling-vm-communication

**Comment by zhengbaowen** [comment]
got it. thanks for your explanation.
